[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 999999
fs_permissions = [{ access = "read", path = "test/fixtures" }]
no-commit = true
[fmt]
sort_imports = true
wrap_comments = true
line_length = 140
